### ISSUE TITLE
Question: read group assignment in align_trim

### ISSUE THREAD

**Issue by gianfilippo** [artic-network/fieldbioinformatics#101]
Hi,

I am just learning how to process Nanopore sequencing data. I am starting from a FASTQ file and trying to understand the artic pipeline.
 
Could you please explain me how align_trim assigns the read groups ?

Thanks

**Comment by kakuk9** [comment]
Hi, I am not a developer, but I also had the same question.
According to the artc [docs](https://artic.readthedocs.io/en/latest/minion/#core-pipeline) here, during alignment post-processing, it would do "using the derived amplicon, assign each read a read group based on the primer pool".
