### ISSUE TITLE
Longshot `thread 'main' panicked at 'assertion failed: p <= 0.0'` error: possible to update longshot?

### ISSUE THREAD

**Issue by KatSteinke** [artic-network/fieldbioinformatics#109]
Would it be possible to use a newer version of longshot? Since January I've been intermittently getting `thread 'main' panicked at 'assertion failed: p <= 0.0'` errors when using longshot, which should be fixed in longshot 0.4.3 and up (see the [relevant issue](https://github.com/pjedge/longshot/issues/43) there). However, ARTIC has longshot 0.4.1 pinned as a dependency. With [longshot 0.4.5 now available on conda](https://anaconda.org/bioconda/longshot), would it be possible for ARTIC to use a higher version at some point to avoid this issue?

**Comment by BioWilko** [comment]
I'll test a version `>=0.4.3` to ensure full compatibility but assuming all is well I will update the pinned version with the next conda release, however if you wish to try this locally you can do so by installing from source and updating the version in `environment.yml` prior to solving the conda environment.

**Comment by KatSteinke** [comment]
I've finally gotten around to trying this for myself locally. Have been trying it with something that reliably fails using longshot 0.4.1 and it works with longshot 0.4.5, and the update doesn't break my usual test dataset either, so I'll go ahead and  create a pull request.

**Comment by BioWilko** [comment]
Version 1.2.3 now pins a version of longshot >= 0.4.5 to fix this and a few other errors.
