### ISSUE TITLE
Error with medaka consensus

### ISSUE THREAD

**Issue by lqhungpt** [artic-network/fieldbioinformatics#115]
When I ran artic with command line on my MacBook M1 Pro chip as bellow:

artic minion --medaka --medaka-model r941_min_high_g360 --normalise 50 --threads 32 --scheme-directory ~/fieldbioinformatics/test-data/primer-schemes/ --read-file /Users/hungluong/passv12.trimmed.fastq.gz ncv1/V1 abcd

I got error after running medaka consensus as bellow:

Running: medaka consensus --model r941_min_high_g360 --threads 32 --chunk_len 800 --chunk_ovlp 400 --RG 2 abcd.trimmed.rg.sorted.bam abcd.2.hdf
Command failed:medaka consensus --model r941_min_high_g360 --threads 32 --chunk_len 800 --chunk_ovlp 400 --RG 2 abcd.trimmed.rg.sorted.bam abcd.2.hdf

**Comment by BioWilko** [comment]
Hi @lqhungpt without any more information I can't really help, if you run `medaka consensus --model r941_min_high_g360 --threads 32 --chunk_len 800 --chunk_ovlp 400 --RG 2 abcd.trimmed.rg.sorted.bam abcd.2.hdf` in the directory you ran the pipeline  when encountering this error initially you should get a much more informative error.
