### ISSUE TITLE
What is the default mindepth ?

### ISSUE THREAD

**Issue by Hugsh** [artic-network/fieldbioinformatics#120]
Hello,

Using the "artic minion" command, I'm wondering about if there is a default value for the minimum depth.

To be more precise, searching into the code I deduced that the choice for a nucleotide to be fixed to "N" in the final sequence is done at the depth mask level and thanks to the associated script "make_depth_mask.py". Then I found the "minDepth" parameter I suspect to be the little guy I was searching for. 

We are actually analyzing ambiguous sequences and really need to go into detail. I don't know if I'm close to the answer or even missing an obviousness but choose to ask you.

**Can you please tell me where to find this minimum depth info ?**

Best regards

**Comment by BioWilko** [comment]
Hello the minimum depth default value is 20x as can be seen here: https://github.com/artic-network/fieldbioinformatics/blob/98241267d65eb76a98d11f3e41b6aeb71da68253/artic/make_depth_mask.py#L181

**Comment by Hugsh** [comment]
Dear @BioWilko,

Indeed, It's too bad I didn't zoom out the code.

Many thanks for your answer !

I have a practical example of a sequence which seems covered (according to the "coverage_mask.txt" file and the trimmed sorted bam visualization on IGV) on a range of positions but with "N" in the final consensus sequence.

Do you wish me to open a new issue for that or do you prefer to modify the present one ?

**Comment by BioWilko** [comment]
Can you check the failed variant VCF? If a variant fails filtering it is replaced by an N in the consensus. If that is the case it is the pipeline functioning as intended.

**Comment by Hugsh** [comment]
The linked variant is in the corresponding  <id>.fail.vcf as you suggested.

Thank you for the precision and your helpful support !

Have a great day.
