### ISSUE TITLE
Conda recipe for 1.2.3 not working

### ISSUE THREAD

**Issue by tavareshugo** [artic-network/fieldbioinformatics#122]
Hi, 

the `conda` recipe for the latest version of `artic` does not seem to work:

```bash
mamba create -n artic artic=1.2.3
```

Gives me: 

```
Encountered problems while solving:
  - package artic-1.2.3-pyhdfd78af_0 requires artic-tools 0.2.6.*, but none of the providers can be installed
```

The same command works fine with `artic=1.2.2`. 

This affects workflows such as [viralrecon](https://github.com/nf-core/viralrecon), which cannot be updated to use the latest version of the software (and therefore do not have the latest medaka models available). 

I could not track down the exact problem with [the recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/artic/meta.yaml), but maybe someone more experienced can pick it up more easily. 

----

This may be related to #116

**Comment by BioWilko** [comment]
Hello, the conda recipe does indeed work if you instruct conda (or mamba) to use the bioconda and conda-forge channels like: `mamba create -n artic -c bioconda -c conda-forge artic=1.2.3` [as it states in the readme](https://github.com/artic-network/fieldbioinformatics#:~:text=conda%20install%20%2Dc%20bioconda%20%2Dc%20conda%2Dforge%20artic).

**Comment by tavareshugo** [comment]
@BioWilko thanks for looking into it. 
Sorry, maybe I have something wrong with my setup then... 
I'm testing on a fresh Ubuntu 22.04 image and it fails for me. 

This is my initial setup:

```bash
# install miniconda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b
rm Miniconda3-latest-Linux-x86_64.sh
export PATH="$HOME/miniconda3/bin/:$PATH"
conda init # adds conda to .bashrc

# channels
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict

# mamba
conda install -y mamba
```

If I try your command: 

```bash
mamba create -n artic -c bioconda -c conda-forge artic=1.2.3
```

If fails, for both `1.2.3` and `1.2.2` with error: 

```
Encountered problems while solving:
  - package artic-1.2.2-pyhdfd78af_0 requires biopython 1.76.*, but none of the providers can be installed
```

I guess this is because of the order of the channels, as bioconda wants strict priority as `conda-forge > bioconda > defaults`. 
So, this command instead works for `1.2.2` (in fact, I wouldn't even have to define the channels here, as I've already ran config above): 

```bash
mamba create -n artic -c conda-forge -c bioconda artic=1.2.2
```

But for me, `1.2.3` still does not work:

```bash
mamba create -n artic -c conda-forge -c bioconda artic=1.2.3
```

```
Encountered problems while solving:
  - package artic-1.2.3-pyhdfd78af_0 requires artic-tools 0.2.6.*, but none of the providers can be installed
```

I'll keep trying to troubleshoot, but thanks for your help.

**Comment by BioWilko** [comment]
Your channel priority should be set to flexible in almost all cases.

**Comment by tavareshugo** [comment]
Ah, yes that does it! 🎉 
I wonder if it's worth adding a note to the README, maybe adding: 

```
conda config --set channel_priority false
```

Just because the [bioconda docs](https://bioconda.github.io/) recommend setting strict priority, so others may have this issue in the future? 

Thanks again!

**Comment by BioWilko** [comment]
Yeah I'll add a note, we hadn't previously because the default channel priority is flexible but I wasn't aware this is recommended in the bioconda docs.

**Comment by cchapus** [comment]
Hi-

for some reasons, I've still the same issue.

`mamba create -n artic -c bioconda -c conda-forge artic=1.2.3`

gives me the same output:

`  - package artic-1.2.3-pyhdfd78af_0 requires artic-tools 0.2.6.*, but none of the providers can be installed`

As indicated, I've set the channel priority with flexible
```
channel_alias: https://conda.anaconda.org
channel_priority: disabled
channels:
  - conda-forge
  - bioconda
```

It's a fresh install of mambaforge.

**Comment by BioWilko** [comment]
I was able to replicate this and successfully installed artic in a fresh mambaforge install with the following command:
`mamba create -n artic -c bioconda -c conda-forge -c defaults artic=1.2.3`.

Obviously mambaforge not having the `defaults` channel is causing issues with `artic-tools`, I will have a look and see if there's a better workaround.

**Comment by cchapus** [comment]
aaaaah thanks.

I didn't think about that. Not so smart on my part.
