### ISSUE TITLE
no version information available (required by samtools)

### ISSUE THREAD

**Issue by alexahess** [artic-network/fieldbioinformatics#124]
Hello, 

I've installed the pipeline on a new computer, using ubuntu 22.04.2. However, when I try to run the pipeline, the steps using samtools and BCFtools fails. I'm using the 1.2.3 version of the Artic pipeline.

The errors I get for samtools are: 
```
samtools: /home/miks/mambaforge/envs/artic/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/miks/mambaforge/envs/artic/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/miks/mambaforge/envs/artic/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
```
This error does not happen when I run samtools 1.16, only for 1.15 which is part of the environment. 

and for BCFtools 
```
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
```
Do you have any idea of how to fix this?

Regards,
Alexander

**Comment by BioWilko** [comment]
This looks like a weird conda issue, how exactly have you installed conda and what is the exact command you used to install the pipeline?

**Comment by Fight-a-tiger-in-the-mountain** [comment]
Hello, I also encountered the following problems, may I ask if you have solved them

$/path/to/leafcutter-master/scripts/bam2junc.sh SRR12705760.bam 
samtools: /work/home//miniconda3/bin/../lib/libtinfo.so.6: no version information available (required by samtools)
samtools: /work/home//miniconda3/bin/../lib/libncurses.so.6: no version information available (required by samtools)

**Comment by Jiachen-Wang-fudan** [comment]
I found that this doesn't seem to affect usage, so I'd like to ask if this bug will have any impact if it's not fixed

**Comment by Fight-a-tiger-in-the-mountain** [comment]
收到

**Comment by Fight-a-tiger-in-the-mountain** [comment]
收到
