### ISSUE TITLE
Conda environment set up

### ISSUE THREAD

**Issue by zkkhalil** [artic-network/fieldbioinformatics#130]
Hello,

I am attempting to set up the conda environment and I keep running into incompatibility issues

`Output:
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
├─ artic-tools 0.2.6**  is installable and it requires
│  └─ boost-cpp >=1.70.0,<1.70.1.0a0  with the potential options
│     ├─ boost-cpp 1.70.0 would require
│     │  └─ icu >=67.1,<68.0a0 , which can be installed;
│     ├─ boost-cpp 1.70.0 would require
│     │  └─ icu >=64.2,<65.0a0 , which can be installed;
│     └─ boost-cpp 1.70.0 would require
│        └─ icu >=58.2,<59.0a0 , which can be installed;
└─ medaka 1.8.0**  is not installable because it requires
   └─ tensorflow >=2.8.0,<2.9.dev0  but there are no viable options
      ├─ tensorflow [2.8.0|2.8.1] would require
      │  └─ tensorflow-base [2.8.0 cpu_py310h75e90da_0|2.8.0 cpu_py37h4373017_0|...|2.8.1 cpu_py39h45807a0_0], which requires
      │     └─ icu >=70.1,<71.0a0 , which conflicts with any installable versions previously reported;
      ├─ tensorflow [2.8.0|2.8.1] would require
      │  └─ __cuda, which is missing on the system;
      └─ tensorflow 2.8.2 conflicts with any installable versions previously reported.
`

I tried to play around with the versions using python 3.8.0 and not specifying a certain version of medaka (leaving it as `medaka`. However, I then ran into the following problem:

`  File "/sc/arion/work/khaliz03/snakemake/c6c19c46c4dc4f596c4635e3613cc2a1_/lib/python3.8/site-packages/h5py/__init__.py", line 46, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5t.pyx", line 293, in init h5py.h5t
  File "/sc/arion/work/khaliz03/snakemake/c6c19c46c4dc4f596c4635e3613cc2a1_/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'`

**Comment by BioWilko** [comment]
Can you point me to the repository for this pipeline? I'm specifically interested in the yaml environment definition.
