### ISSUE TITLE
htslib =1.17 dependency PLEASE UPDATE

### ISSUE THREAD

**Issue by robertwhbaldwin** [artic-network/fieldbioinformatics#133]
greetings,
artic has a requirement for htslib = 1.17 (for the newest version). Can that be changed to >=1.18 and <1.20.0 ? Thanks

**Comment by BioWilko** [comment]
I can certainly do so but I need to be told a reason before I do.

Also the environment.yaml file in this repository is just a text file and can be modified if you need to do so (the version on bioconda does not pin htslib).
