### ISSUE TITLE
Catch error associated with malformed primer.bed

### ISSUE THREAD

**Issue by ammaraziz** [artic-network/fieldbioinformatics#144]
Hi,

Thanks for creating and maintaining this amazing fieldsbioinformatics.

I stumbled across this silent bug when running a new primer scheme for MPXV (spiked in yale scheme). The `primer.bed` file was had incorrectly paired primers. See attached as an example. I have deleted `MPXV_4_RIGHT_1` primer.  [primer_malformed.txt](https://github.com/user-attachments/files/17943320/primer_malformed.txt)

Command:
```
artic minion --bed primer_malformed.bed --ref reference.fasta --read-file barcode81.fastq.gz malformed/barcode81
```

Pipeline output: [malformed.log.txt](https://github.com/user-attachments/files/17943318/malformed.log.txt)

The pipeline proceeds as normal all the way to completion. It's hard to detect where the error is until you inspect `{sample}.alignreport.er`:

````
{snipped}
4b769c6e-cea7-4692-8462-2206a1d834c6 skipped as mapping quality below threshold
e8573c97-463b-41b8-95c5-3d4ac36c7204 skipped as mapping quality below threshold
1fd0f9b4-2602-4c6c-b359-4578c85cc74a skipped as mapping quality below threshold
2c0e1932-e8cf-44dc-8220-66e54b335533 skipped as mapping quality below threshold
Traceback (most recent call last):
  File "/home/amar/miniforge3/envs/artic/bin/align_trim", line 10, in <module>
    sys.exit(main())
  File "/home/amar/miniforge3/envs/artic/lib/python3.9/site-packages/artic/align_trim.py", line 570, in main
    go(args)
  File "/home/amar/miniforge3/envs/artic/lib/python3.9/site-packages/artic/align_trim.py", line 509, in go
    output_segments, mean_amp_depths = normalise(
  File "/home/amar/miniforge3/envs/artic/lib/python3.9/site-packages/artic/align_trim.py", line 383, in normalise
    amplicons = generate_amplicons(bed)
  File "/home/amar/miniforge3/envs/artic/lib/python3.9/site-packages/artic/align_trim.py", line 352, in generate_amplicons
    raise ValueError(f"Primer scheme for amplicon {amplicon} is incomplete")
ValueError: Primer scheme for amplicon 4 is incomplete
````

The command should hard fail, stopping completely but it currently continues on producing an empty `.bam` file. I think the reason why `align_trim` doesn't hard fail stopping the process is because it's being run in a pipe (and `pipefail` is not set in bash).

A simple solution (I think) would be to append pipefail to enable 'strict' bash mode like so:

```
'/bin/bash -c set -o pipefail {rest of the command}'
```

A better solution would be to write a function to check `primer.bed` for possible common errors, happy to write something if you think this is a good idea.

Thanks,

Ammar

**Comment by BioWilko** [comment]
Thanks for reporting the problem Ammar

There is already bed file validation in align_trim (hence the exception raised in your issue) so the issue was more that this exception was hidden from users, I've made sure the exception is raised visibly to users by significantly reducing the verbosity of align_trim and removing the stderr logfile. I've also split out the align_trim command into two to avoid silent errors.

**Comment by ammaraziz** [comment]
Amazing! Thanks Sam.
