### ISSUE TITLE
Please port to Python3 

### ISSUE THREAD

**Issue by M-Artemisia** [artic-network/fieldbioinformatics#24]
Hello,
The Debian Med team is packaging fieldbioinformatics for official Debian. The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL. If you are interested that we package and maintain fieldbioinformatics in official Debian (and that users of other modern distributions will have no problems to install fieldbioinformatics on their systems) I'd recommend you port your code to Python3. The 2to3 tool might be of great help here.
Kind regards, 
Mali

**Comment by will-rowe** [comment]
Hi @M-Artemisia. Thanks for getting in touch - and for offering to package this project!

There shouldn't be any Python2 in the source code for the current and future releases of fieldbioinformatics. We've kept a few pieces of Python2 under `artic/deprecated` for  posterity's sake but this isn't used in the current application. Is this a problem for packaging? We can look at removing it if needs be.

**Comment by M-Artemisia** [comment]
Thanks for your reply. 
We are packaging the latest stable release V1.0.0, which is not in python3. As the next stable version (V1.1.0) would be in python3, I hope the v1.1.0-rc be released soon, so we could package it properly.
Also, there is not any problem about the `artic/deprecated` directory in	the next release. As all the python2 codes are gathered in a dedicated directory, it could be handled easily in packaging. 

Hope to see the next stable relese soon,
best regards,

**Comment by will-rowe** [comment]
Hi @M-Artemisia

There is now a new release: https://github.com/artic-network/fieldbioinformatics/releases/tag/1.1.1

I hope this clears up the Python2/3 issues. Thank you again for packaging this for Debian!

**Comment by will-rowe** [comment]
Okay - I think we can close this now. Please re-open if you need anything else.

**Comment by M-Artemisia** [comment]
Hi Will,
thank you for your effort and for letting me know about the new release.
I'll continue the packaging process on the new release, soon.

Kind regards,
