### ISSUE TITLE
Not seeing default argument values in pipeline.py

### ISSUE THREAD

**Issue by jbeaulaurier** [artic-network/fieldbioinformatics#27]
Hello,

I see that there is some code in place using ArgumentParserWithDefaults to include the specified argument defaults in the help string, but it's not picking them up for me. As a result, all the default values are hidden when you use `artic <subcommand> -h`. This tripped me up because I thought that simply removing `--normalise <N>` from `artic minion` would drop the normalisation step (instead it defaulted to `--normalise 100`). Not sure where the argparser it's going wrong, but it'd be great if someone with a sharper eye than me could take a look.

Thanks,
John

**Comment by nickloman** [comment]
There is a default value set of 100 in there. I think if you set normalise to 0 it will do what you want!
