### ISSUE TITLE
artic_make_depth_mask now ignoring RG1 coverages

### ISSUE THREAD

**Issue by egonozer** [artic-network/fieldbioinformatics#34]
Since the new update to artic_make_depth_mask, the resulting coverage_mask.txt file masks any positions covered by read group 1 amplicons, even if they have sufficient coverage. Only regions covered by read group 2 amplicons are unmasked. When the script is run without the "--store-rg-depths" option, the resulting coverage_mask.txt file is correct.

**Comment by will-rowe** [comment]
Thanks @egonozer - my bad python skills leading to a variable name collision I think, causing an over-write of the global depth values. Will push a fix now - what's a Friday night without finding a bug in deployment?

**Comment by egonozer** [comment]
Thanks. I’m a Perl guy so you’ll get no criticism from me!

- E

Egon A. Ozer, MD PhD
Assistant Professor
Department of Medicine, Division of Infectious Diseases
Northwestern University Feinberg School of Medicine
e-ozer@northwestern.edu<mailto:e-ozer@northwestern.edu>

This email is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged and confidential. If the reader of this email message is not the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is prohibited. If you have received this email in error, please notify the sender and destroy/delete all copies of the transmittal.

**Comment by nickloman** [comment]
thanks very much for spotting this so quickly, fixed in latest master
