### ISSUE TITLE
remove ebov-flongle/fast5_pass

### ISSUE THREAD

**Issue by tolot27** [artic-network/fieldbioinformatics#38]
Please can you remove or exclude the `test-data/ebov-flongle/fast5_pass` folder? It has a size of nearly 1 GB and it takes very long to clone it during conda install or update and sometimes breaks on slow connections.
Unfortunately, it is neither possible to shallow clone a git repository using pip nor using filters introduced with git 2.19.

**Comment by will-rowe** [comment]
Hi @tolot27 

Yes - that is planned. It's there until we make the next release and the other tests will supersede it
