### ISSUE TITLE
artic minion pyhton3.6 error

### ISSUE THREAD

**Issue by shashibioinfo143** [artic-network/fieldbioinformatics#49]
Hi sir,

I have installed Miniconda Python 3.6 version, conda version 4.8.3. i got following error if you can please resolve this issue.

Thanks

artic minion --threads 8 --scheme-directory ~/artic-ncov2019/primer_schemes --read-file sample01.fastq --sequencing-summary /data/COVID_SET1/COVID-19/merged_fastq_files/  artic-ncov2019/primer_schemes/   nCoV-2019/V3  sample01 

Traceback (most recent call last):
  File "/home/grid/miniconda3/envs/artic-ncov2019/bin/artic", line 10, in <module>
    sys.exit(main())
  File "/home/grid/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 216, in main
    args.func(parser, args)
  File "/home/grid/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 35, in run_subtool
    submodule.run(parser, args)
  File "/home/grid/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/minion.py", line 23, in run
    scheme_name, scheme_version = args.scheme.split('/')
ValueError: too many values to unpack (expected 2)

**Comment by nickloman** [comment]
The command has an extra argument `artic-ncov2019/primer_schemes/` which should not be present, i.e. it should be:

`artic minion --threads 8 --scheme-directory ~/artic-ncov2019/primer_schemes --read-file sample01.fastq --sequencing-summary /data/COVID_SET1/COVID-19/merged_fastq_files/ nCoV-2019/V3 sample01`

**Comment by nickloman** [comment]
Additionally, unless you are using `--medaka` you will need to add the `fast5-directory` argument, and the `--sequencing-summary`should point to a sequencing summary not a directory.

**Comment by shashibioinfo143** [comment]
Thank you so much for response
The issue is resolved.
If you can let me know document of output results explanation from artic workflow

**Comment by will-rowe** [comment]
Hi @shashibioinfo143 - sorry for missing this.

You can find details on the output files in the [SOP](https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html) - I'll update the docs to give more details too.

Closing this issue now as the original problem is resolved.
