### ISSUE TITLE
Compatibility between new MinKNOW and Artic pipeline 

### ISSUE THREAD

**Issue by Serka-M** [artic-network/fieldbioinformatics#54]
Hello,

With the release of the new MinKNOW, basecalling models for Guppy 4.0  were made the default.

Since the Medaka software used with the Artic pipeline seems to be based on older versions of Guppy,
we were wondering whether it is fine to use Fastq files from the new MinKNOW (HAC in real-time GPU) with your pipeline?

**Comment by nickloman** [comment]
I don't see any particular reason why this wouldn't work directly but we have not yet tested it. But please ensure double barcoding mode is enabled.

**Comment by sagrudd** [comment]
Hi @nickloman - I am going to make a PR to address this potential issue

**Comment by will-rowe** [comment]
I think we can close this now thanks to @sagrudd's PR (now merged): https://github.com/artic-network/fieldbioinformatics/pull/55
