### ISSUE TITLE
SARS-CoV-2 visualization

### ISSUE THREAD

**Issue by AgustinPardo** [artic-network/fieldbioinformatics#56]
Hello, I see a new CoV-2 visualization tool in https://artic.network/hCoV-19-viz

Is there a possibility to use it?

Regards

Agustin

**Comment by jtmccr1** [comment]
Hello Agustin,

Thank you for your interest in this. We have plans to make a small javascript library that would make it easy to reproduce this and similar figures, but it's not done yet. This repository pulls its figure from https://github.com/jtmccr1/sars2 . Which I see you have found as well. It relies on https://github.com/jtmccr1/figtreejs-react which is a react based version of https://github.com/rambaut/figtree.js. Either of those repositories can be used to make similar figures. They are in active development and not yet stable. There's no guarantee that what works today will work tomorrow. That said there's nothing stopping you from taking a look around and you are more than welcome to try them out.
