### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by fabgenomics** [artic-network/fieldbioinformatics#64]
Hi,
I tried to install the pipeline and didn't find artic in my env.
It seems to have an error on the environment.yml
dependencies:
  - artic-porechop==0.3.2pre

I solved by separate artic from porechop.
Cheers

**Comment by will-rowe** [comment]
Hi - my fault for unclear install instructions. I have updated the README now.

The environment in this repo provides only the dependencies, you need to then activate that environment and install artic using `python setup.py install`.

**Comment by fabgenomics** [comment]
Thanks
