### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by will-rowe** [artic-network/fieldbioinformatics#69]
An issue to track progress on the next minor release. This is in response to the CLIMB/ARTIC workshop where there were some usability issues and improvement suggestions. Features to target for the next minor release (1.3.0):

QC report:
- [x] parameterise the coverage cutoff on the amplicon plot using the `--depth` flag provided to the `artic_make_depth_mask`. This is currently set to 50 on the plot but actually 20 is the minimum read depth used in the depth mask.
- [x] add more meaningful VCF fail output - include vars from the PASS and FAIL files
- [x] add some coverage stats from the alignment file (trimmed / primertrimmed)

Software:
- [x] update to the new medaka release on PyPi - test it and wait for conda recipe before releasing 1.3.0
- [x] optional - check the output of latest medaka vs longshot and evaluate if longshot can be replaced

Minion:
- [x] parameterise minimum read depth for masking, this will feed into the amplicon plotting
- [x] add the QC report to the core pipeline (remove requirement of `--strict`)
- [x] enforce full length amplicon alignment during align_trim when pipeline run with `--strict`

VCF report:
- [x] update the report to be more intuitive and informative (issue for [artic-tools](https://github.com/will-rowe/artic-tools))

README/Tests:
- [x] looks like Travis is retiring/limiting free service plan? Try GitHub actions out instead
- [x] add the DOI to the readme, which has been minted since 1.2.0

**Comment by will-rowe** [comment]
Have updated [ARTIC tools]() to output more stats from VCF file and in TSV format, so we can parse those in this minion pipeline and add them to the MultiQC report.

New release is [v0.3.0](https://github.com/will-rowe/artic-tools/releases/tag/v0.3.0), updating conda now

**Comment by mattloose** [comment]
Which release is currently on conda?

**Comment by will-rowe** [comment]
1.2.1

**Comment by will-rowe** [comment]
Sorry - my earlier comment is in relation to artic-tools, which is a small utility program I'm maintaining for managing primer scheme tasks.

artic-tools == 0.3.0
artic == 1.2.1

**Comment by rpetit3** [comment]
Hello! Is there a timeline on v1.3.0? We've been using the dev branch for a while, but I'd like to get v1.3.0 into Bioconda. Thank you!
