### ISSUE TITLE
align_trim strand consideration

### ISSUE THREAD

**Issue by chienchi** [artic-network/fieldbioinformatics#72]
When doing align_trim, I noticed a read could be soft-clipped by both forward and reverse primers.  

Sorry, I am not familiar with sequencing protocol in detailed, but should the align_trim take the strand into account while doing the trimming, so forward primers are trimmed only from forward strand and reverse primers are trimmed from reverse strand?

before line 231: if not segment.is_reverse:
before line 243: if segment.is_reverse:

**Comment by nickloman** [comment]
Hi

Both the primers will be present at each end of the read, regardless of strand, so no need to account for this specifically.

**Comment by chienchi** [comment]
Got it. Thank you.
