### ISSUE TITLE
Tmp file issue while using medaka instead of longshot

### ISSUE THREAD

**Issue by amandawarr** [artic-network/fieldbioinformatics#74]
I have been running a bunch of viruses in parallel using --no-longshot from the same directory. Medaka appears to very briefly have a tmp file that is not uniquely named (tmp.medaka-annotate.vcf), and if several jobs get there at the same time mayhem ensues. It works fine if run individually.

Point of failure:
```
Running: medaka tools annotate --pad 25 --RG nCoV-2019_2 barcode22/EDB14609.nCoV-2019_2.vcf primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta barcode22/EDB14609.trimmed.rg.sorted.bam tmp.medaka-annotate.vcf
Running: mv tmp.medaka-annotate.vcf barcode22/EDB14609.nCoV-2019_2.vcf
Command failed:mv tmp.medaka-annotate.vcf barcode22/EDB14609.nCoV-2019_2.vcf
```

This seems suboptimal :)

**Comment by nickloman** [comment]
Ugh! Nice spot.

**Comment by will-rowe** [comment]
thanks - this will be fixed in the next release
