### ISSUE TITLE
annotation to the vcf file to receive the mutations amino acids and locations

### ISSUE THREAD

**Issue by dinavb** [artic-network/fieldbioinformatics#75]
How can I annotate further the vcf file to receive not only the genomic locations but also the mutations in format of  amino acid changes?

**Comment by will-rowe** [comment]
Hi @dinavb - thanks for getting in touch. I'm afraid we don't offer that functionality at the moment in artic. You could look at using an annotation tool on the VCF output of artic. Maybe something like: https://github.com/rpetit3/vcf-annotator
