### ISSUE TITLE
Multiqc issue

### ISSUE THREAD

**Issue by hannahgoldswain** [artic-network/fieldbioinformatics#76]
My colleague is using an older version of this pipeline and gets barplots however I see you've deleted this feature and installed multiqc. When I run multiqc I am not getting any files. How do I run multiqc or get the barplots used in the old version? Thanks!

**Comment by will-rowe** [comment]
Hi @hannahgoldswain 

Thanks for getting in touch. In the current version of the pipeline, you have to run minion with `--strict` to generate the summary stats that multiqc needs to generate the report.

In the new version (1.3.0), which should be released soon, the summary stats will be generated by default.

**Comment by hannahgoldswain** [comment]
Thanks Will, that's really helpful!
