### ISSUE TITLE
EPI2ME ARTIC failing for Midnight primers

### ISSUE THREAD

**Issue by MMitali13** [artic-network/fieldbioinformatics#95]
I had recently did a Nanopore sequencing run for SARS-CoV-2 in MinION with midnight primers 1200 bp amplicons (Nikki Freed protocol) and native barcoding kit (EXP-NBD96). I have earlier used EPI2ME pipeline for data analysis using ARTIC V3 primers. This time the ARTIC analysis is failing for Midnight primers. I put my queries on the community, where one of the users is saying I should use the recommended wf-ARTIC bioinformatics pipeline with rapid barcodes. Can someone please support me with the data analysis. Which bioinformatics pipeline I should use here and how to fix this problem?

Thanks in advance!

**Comment by Psy-Fer** [comment]
I came here looking for something else. But if you want a quick fix that isn't just running the regular artic pipeline, you could try InterArtic over here.

https://github.com/Psy-Fer/interARTIC

It contains options for midnight and native barcodes.

Hope that helps.
