### ISSUE TITLE
V1200/midnight primer scheme

### ISSUE THREAD

**Issue by rebeelouise** [artic-network/fieldbioinformatics#98]
Hi guys,

Been testing out the midnight primers in our lab which look good when running the epi2me analysis, however, I am now at the command line and it is saying it does not recognise the V1200 scheme... I have added this to the directory with the other schemes locally. Is there a reason why these aren't included in the pipeline? Should I be using a different pipeline?

Thanks :)

**Comment by BioWilko** [comment]
Hi Rebee

Sorry for the late reply but on the off chance that you're still having this problem if you follow the directory structure described in [this comment](https://github.com/artic-network/fieldbioinformatics/issues/96#issuecomment-963688688) it should be able to find the scheme.

Sam W
